config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path(@flat)
    else
      render :new
    end
  end


  def show
  end


  def edit
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :price_per_night, :address, :number_of_guests, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
  <p>AirBnB</p>
  <p class="form-inline"><%= link_to "Add Flat", new_flat_path, class: "btn btn-dark" %></p>
</nav>
<div class="container">
  <div class="row justify-content-center">
    <h1>Flats</h1>
  </div>
  <div class="row justify-content-center">
    <p>You've searched for . We found 3 flats for you.</p>
  </div>
  <div class="row justify-content-center">
    <% @flats.each do |flat| %>
    <div class="card col-3 flat-card">
      <h3><%= flat.name %></h3>
      <p><%= flat.address %></p>
      <p><i class="fas fa-user-friends"></i><%= flat.number_of_guests %> <i class="fas fa-euro-sign"></i><%= flat.price_per_night %></p>
      <p><%= link_to "More Info", flat_path(flat.id) %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add a Flat!</h1>

  <%= simple_form_for [@flat] do |f| %>
    <%= f.input :name %>
    <%= f.input :price_per_night %>
    <%= f.input :address %>
    <%= f.input :number_of_guests %>
    <%= f.input :description %>
    <%= f.submit "Add Flat", class: "btn btn-primary" %>
    <%= link_to "Home", flats_path, class: 'btn btn-dark' %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container border">
  <h1 class="col-6"><%= @flat.name %></h1>

    <p class="col-6"><i class="fas fa-user-friends"></i><%= @flat.number_of_guests %> <i class="fas fa-euro-sign"></i><%= @flat.price_per_night %></p>
  <p class="col-6"><%= @flat.description %></p>

  <%= link_to "Home", flats_path, class: "btn btn-sm btn-dark" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>